// Public proxy for the DSAR export download. The signed URL params are
// generated by FastAPI and re-verified by FastAPI when this hits.
// No auth here — the signature IS the auth, with a 1-hour TTL.

const PIPELINE_URL = process.env.PIPELINE_URL ?? 'http://localhost:8000'

export async function GET(req: Request) {
  const url = new URL(req.url)
  const upstream = new URL(`${PIPELINE_URL}/data-rights/export`)
  for (const [k, v] of url.searchParams) upstream.searchParams.set(k, v)

  const res = await fetch(upstream.toString(), { cache: 'no-store' })
  const body = await res.arrayBuffer()
  return new Response(body, {
    status: res.status,
    headers: {
      'Content-Type': res.headers.get('content-type') ?? 'application/json',
      'Content-Disposition': res.headers.get('content-disposition') ?? 'attachment',
    },
  })
}
