"""
Render Basanite reports (hirer + candidate) as downloadable PDFs via WeasyPrint.
Both shapes share the same visual language; the hirer variant carries scoring +
evidence, the candidate variant carries constructive feedback.
"""
from html import escape


def _format_key(key: str) -> str:
    """Turn 'technical_depth' into 'Technical Depth' for report headings."""
    if not key:
        return ""
    return " ".join(word.capitalize() for word in str(key).split("_") if word)


BASE_CSS = """
@page { size: A4; margin: 22mm 20mm 20mm 20mm; }
body { font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       font-size: 10.5pt; color: #1a1a1a; line-height: 1.55; }
header.doc { border-bottom: 1px solid #e5dccd; padding-bottom: 12px; margin-bottom: 20px;
             display: flex; justify-content: space-between; align-items: baseline; }
header.doc .brand { font-family: 'DM Serif Display', Georgia, serif; font-size: 14pt; color: #0b1f3d; }
header.doc .meta { font-size: 9pt; color: #8a7a5e; text-transform: uppercase; letter-spacing: 0.1em; }
h1 { font-family: 'DM Serif Display', Georgia, serif; font-size: 22pt; color: #0b1f3d;
     margin: 0 0 4px 0; font-weight: normal; }
.sub { color: #555; font-size: 11pt; margin-bottom: 24px; }
h2 { font-family: 'DM Serif Display', Georgia, serif; font-size: 14pt; color: #0b1f3d;
     margin-top: 24px; margin-bottom: 8px; font-weight: normal; border-bottom: 1px solid #eee;
     padding-bottom: 4px; }
h3 { font-size: 11pt; color: #0b1f3d; margin-top: 14px; margin-bottom: 4px; }
p { margin: 0 0 10px 0; }
ul { margin: 0 0 10px 0; padding-left: 18px; }
li { margin-bottom: 4px; }
blockquote { border-left: 3px solid #c49a2f; margin: 8px 0 12px 0; padding: 6px 12px;
             color: #333; background: #faf7f2; font-style: italic; }
.score-row { display: flex; justify-content: space-between; align-items: baseline;
             padding: 8px 0; border-bottom: 1px dashed #eee; }
.score-row:last-child { border-bottom: none; }
.score-name { font-weight: 600; color: #0b1f3d; }
.score-value { font-family: 'Courier New', monospace; font-size: 10pt; color: #c49a2f; }
.quote-basis { color: #555; font-size: 10pt; margin-top: 2px; }
.notes { color: #8a7a5e; font-size: 10pt; margin-top: 2px; font-style: italic; }
footer.doc { margin-top: 28px; padding-top: 10px; border-top: 1px solid #eee;
             color: #8a7a5e; font-size: 8.5pt; }
"""


def _bullets(items: list) -> str:
    if not items:
        return ""
    items = [escape(str(i).strip()) for i in items if str(i).strip()]
    if not items:
        return ""
    return "<ul>" + "".join(f"<li>{i}</li>" for i in items) + "</ul>"


def _header(role_title: str, candidate_name: str, kind: str) -> str:
    return f"""
<header class="doc">
  <span class="brand">Basanite</span>
  <span class="meta">{escape(kind)} report · {escape(candidate_name)} · {escape(role_title)}</span>
</header>
"""


def _footer() -> str:
    return """
<footer class="doc">
  Generated by Basanite, AI conducted technical interviews.
  Scores are grounded in specific candidate quotes. Flag any dimension needing expert verification.
</footer>
"""


def _candidate_html(role_title: str, candidate_name: str, report: dict) -> str:
    summary = escape(report.get("summary") or "")
    strengths = _bullets(report.get("strengths") or [])
    areas = _bullets(report.get("areas_for_development") or [])
    overall = escape(report.get("overall_impression") or "")

    body = []
    if summary:
        body.append(f"<h2>Summary</h2><p>{summary}</p>")
    if strengths:
        body.append(f"<h2>What you did well</h2>{strengths}")
    if areas:
        body.append(f"<h2>Areas for development</h2>{areas}")
    if overall:
        body.append(f"<h2>Overall</h2><blockquote>{overall}</blockquote>")
    if not body:
        body.append("<p>No feedback content available.</p>")

    return f"""
<!doctype html>
<html><head><meta charset="utf-8"><style>{BASE_CSS}</style></head>
<body>
  {_header(role_title, candidate_name, 'Candidate')}
  <h1>Your feedback report</h1>
  <p class="sub">{escape(candidate_name)} · {escape(role_title)}</p>
  {''.join(body)}
  {_footer()}
</body></html>
"""


def _hirer_html(role_title: str, candidate_name: str, report: dict) -> str:
    body: list[str] = []

    summary = report.get("comprehensive_assessment") or {}
    one_liner = escape(summary.get("one_sentence_summary") or "")
    if one_liner:
        body.append(f"<blockquote>{one_liner}</blockquote>")

    scoring = report.get("scoring_summary") or []
    if scoring:
        rows = []
        for s in scoring:
            raw_name = s.get("dimension") or s.get("name") or ""
            name = escape(_format_key(raw_name))
            score = s.get("score")
            score_str = f"{score}/5" if isinstance(score, (int, float)) else escape(str(score or ""))
            quote = escape(str(s.get("quotation_basis") or ""))
            notes = escape(str(s.get("notes") or ""))
            quote_html = f'<div class="quote-basis">&ldquo;{quote}&rdquo;</div>' if quote else ""
            notes_html = f'<div class="notes">{notes}</div>' if notes else ""
            rows.append(
                f'<div class="score-row">'
                f'<div><div class="score-name">{name}</div>{quote_html}{notes_html}</div>'
                f'<div class="score-value">{score_str}</div>'
                f'</div>'
            )
        body.append("<h2>Dimension scores</h2>" + "".join(rows))

    excerpts = report.get("top_excerpts") or []
    if excerpts:
        items = []
        for e in excerpts:
            if isinstance(e, dict):
                quote = escape(str(e.get("quote") or e.get("excerpt") or ""))
                why = escape(str(e.get("why") or e.get("reason") or e.get("why_selected") or ""))
                why_html = f"<p>{why}</p>" if why else ""
                items.append(f"<blockquote>{quote}</blockquote>{why_html}")
            else:
                items.append(f"<blockquote>{escape(str(e))}</blockquote>")
        body.append("<h2>Top excerpts</h2>" + "".join(items))

    cap = report.get("capability_map") or {}
    if cap:
        sections = [
            ("Technical depth", cap.get("technical_depth")),
            ("Transfer capability", cap.get("transfer_capability")),
            ("Blind spots", cap.get("blind_spots")),
            ("Requires expert verification", cap.get("expert_verification_nodes")),
        ]
        parts = []
        for title, value in sections:
            if not value:
                continue
            if isinstance(value, list):
                parts.append(f"<h3>{escape(title)}</h3>{_bullets(value)}")
            else:
                parts.append(f"<h3>{escape(title)}</h3><p>{escape(str(value))}</p>")
        if parts:
            body.append("<h2>Capability map</h2>" + "".join(parts))

    risk = summary.get("cheating_risk") if isinstance(summary, dict) else None
    if risk:
        if isinstance(risk, dict):
            level = escape(str(risk.get("level") or ""))
            rationale = escape(str(risk.get("rationale") or ""))
            body.append(f"<h2>Cheating risk</h2><p><strong>{level}</strong>, {rationale}</p>")
        else:
            body.append(f"<h2>Cheating risk</h2><p>{escape(str(risk))}</p>")

    if not body:
        body.append("<p>No report content available.</p>")

    return f"""
<!doctype html>
<html><head><meta charset="utf-8"><style>{BASE_CSS}</style></head>
<body>
  {_header(role_title, candidate_name, 'Hirer')}
  <h1>Assessment report</h1>
  <p class="sub">{escape(candidate_name)} · {escape(role_title)}</p>
  {''.join(body)}
  {_footer()}
</body></html>
"""


def render_report_pdf(
    report_type: str,
    role_title: str,
    candidate_name: str,
    report: dict,
) -> bytes:
    """Return a PDF byte-string for the given report. report_type is 'hirer' or 'candidate'."""
    from weasyprint import HTML
    html = (
        _hirer_html(role_title, candidate_name, report)
        if report_type == "hirer"
        else _candidate_html(role_title, candidate_name, report)
    )
    return HTML(string=html).write_pdf()
