import type { Metadata } from 'next'
import Link from 'next/link'
import { LogoMark } from '@/components/Logo'
import { buildMetadata } from '@/lib/seo'

export const metadata: Metadata = buildMetadata({
  title: 'Terms of Service',
  description: 'Terms governing use of Basanite — eligibility, account responsibilities, AI assessment scope, acceptable use, IP ownership, and governing law.',
  path: '/terms',
})

const TERMS_VERSION = '2026-05-07'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-earth-50">
      <header className="border-b border-earth-200 bg-white">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <LogoMark size={24} dark />
            <span className="font-semibold text-basanite-900 text-sm">Basanite</span>
          </Link>
          <Link href="/dashboard" className="text-xs text-basanite-500 hover:text-basanite-900 transition-colors">
            ← Back to dashboard
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 text-basanite-800">
        <h1 className="font-display text-3xl text-basanite-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-basanite-500 mb-10">Effective {TERMS_VERSION}.</p>

        <p className="text-sm leading-relaxed mb-6">
          These terms govern your use of Basanite. By signing up or taking an assessment you agree to these terms and to the <Link href="/privacy" className="text-gold-600 underline">Privacy Notice</Link>.
        </p>

        <Section title="Who you are contracting with">
          <p>
            Basanite is currently operated as an unincorporated UK venture by its two founders &mdash; <strong>Aditya Shah</strong> and <strong>Lynn Zhao</strong> &mdash; based in the United Kingdom. References to &ldquo;Basanite&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo; in these terms mean those two individuals acting jointly. Until a UK company is incorporated, obligations and liabilities under these terms are owed jointly and severally by the named founders. Once an entity is incorporated we will novate this contract to the new entity and update this page.
          </p>
        </Section>

        <Section title="Eligibility">
          <p>You must be at least 16 years old to use Basanite. Hirer accounts may only be created by individuals authorised to act on behalf of the hiring organisation.</p>
        </Section>

        <Section title="Account responsibilities">
          <ul className="space-y-1 list-disc pl-5">
            <li>Keep your password confidential. Notify us immediately of any unauthorised access.</li>
            <li>Hirers must only invite candidates who have applied to a role at their organisation.</li>
            <li>Don&apos;t use the service to harass, discriminate against, or otherwise mistreat candidates.</li>
          </ul>
        </Section>

        <Section title="AI assessment — what it is and isn&apos;t">
          <p>
            Interviews are conducted and scored by AI. The output is a recommendation, not a hiring decision. Hirers remain solely responsible for any hiring decision and for ensuring it complies with applicable employment and equality law in their jurisdiction. Candidates have the right to request human review (see the <Link href="/privacy" className="text-gold-600 underline">Privacy Notice</Link>).
          </p>
        </Section>

        <Section title="Acceptable use">
          <ul className="space-y-1 list-disc pl-5">
            <li>Don&apos;t attempt to reverse-engineer, scrape, or overload the service.</li>
            <li>Don&apos;t upload malware, illegal content, or content you don&apos;t have rights to.</li>
            <li>Don&apos;t attempt to bypass the AI agent or fraudulently impersonate another candidate.</li>
          </ul>
        </Section>

        <Section title="Intellectual property">
          <p>
            You retain ownership of the CVs, recordings, and content you submit. You grant Basanite a limited licence to host and process that content for the purpose of delivering the service. Reports generated by the AI are made available to the hirer who paid for the assessment.
          </p>
        </Section>

        <Section title="Disclaimers and liability">
          <p>
            The service is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, Basanite is not liable for indirect or consequential losses, including loss of profit or business opportunity, arising from your use of the service. Nothing in these terms limits liability for fraud, gross negligence, or anything that cannot lawfully be excluded.
          </p>
        </Section>

        <Section title="Termination">
          <p>You may close your account at any time. We may suspend or terminate accounts that breach these terms.</p>
        </Section>

        <Section title="Governing law">
          <p>These terms are governed by the laws of England and Wales. Disputes are subject to the exclusive jurisdiction of the courts of England and Wales.</p>
        </Section>

        <Section title="Contact">
          <p><a href="mailto:aditya.shah@basanite.co.uk" className="text-gold-600 underline">aditya.shah@basanite.co.uk</a></p>
        </Section>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display text-xl text-basanite-900 mb-3">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed">{children}</div>
    </section>
  )
}
